apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: manager
  labels:
    app: manager
spec:
  replicas: 1 # Number of replicas
  selector:
    matchLabels:
      app: core
  template:
    metadata:
      name: core
      labels:
        app: core
    spec:
      containers:
      - name: core
        image: grc.io/createstructure/core-createstructure:latest
        imagePullPolicy: "Always"
        volumeMounts:
        - name: auth
          readOnly: true
          mountPath: "/etc/auth"
