.\" This man page for manager
.TH manager "1" "2022-12-27" "manager 10.01.07" "User Commands"
.SH NAME
manager
.SH SYNOPSIS
.B manager - manage manager containers
.br
.B manager [-h | --help] - Help
.br
.B manager [-v | --version] - Version
.br
.B manager [-l | --login] [[-u | --username] [-p | --password] [-sn | --server-name] [-sp | --server-password]] - Login (username is the GitHub username) (password is the GitHub server token with containers permissions)
.SH DESCRIPTION
Repo where there is everything you need for server management
.SH AUTHORS
Castellani Davide (@DavideC03): owner