.\" This man page for manager
.TH manager "1" "2021-07-13" "manager 09.01.13" "User Commands"
.SH NAME
manager
.SH SYNOPSIS
.B manager - manage manager containers
.br
.B manager [-h | --help] - Help
.SH DESCRIPTION
Repo where there is everything you need for server management
.SH AUTHORS
Castellani Davide (@DavideC03): owner