name: Upgrade documentation (Wiki + README.md)
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'releases/*'

jobs:
  UML-export:
    runs-on: ubuntu-latest
    environment:
      name: UML
    steps:
    - uses: actions/checkout@v2
    - name: Export UML    
      continue-on-error: true
      uses: docker://rlespinasse/drawio-export:latest
      with:
        args: -f svg -o ./ docs
    - name: git add & commit & upload repo
      continue-on-error: true
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "help@castellanidavide.it"
        git add *
        git commit -m "Exported UML automatically"
        git push https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git -f

  upgrade-documentation:
    runs-on: ubuntu-latest
    environment:
      name: documentation
    steps:
    - name: Initial setup
      run: |
        sudo apt update -y
        sudo pip install BeautifulSoup4
        {
          git clone --recurse-submodules --depth 1 https://$.GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.wiki.git wiki
        } || {
          mkdir wiki
        }
        git clone --recurse-submodules --depth 1 https://$.GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git -b $(echo ${GITHUB_REF#refs/heads/}) repo
        rm -f wiki/*.md
    - name: Home file
      run: |
        cd wiki
        python3 << EOF
        import requests
        import json
        from bs4 import BeautifulSoup
        def web_request(url):
          """ Make a web request and return the response
          """ 
          return requests.get(url, auth=("$GITHUB_ACTOR", "${{ secrets.GITHUB_TOKEN }}")).text
        def get_json():
          """ Returns the json with description
          """
          return json.loads(web_request("$GITHUB_API_URL/repos/$GITHUB_REPOSITORY"))
        def get_social_img():
          """ Get social image
          """
          try:
            soup = BeautifulSoup(web_request("$GITHUB_SERVER_URL/$GITHUB_REPOSITORY"), 'html.parser')
            return soup.find("meta", property="og:image")["content"]
          except:
            print("Error getting social image")
            return ""
        def get_content():
          """ Returns the file content
          """
          social_img = get_social_img()
          file_content = "## :octocat: Description :octocat:\n"
          file_content += get_json()["description"].replace(". ", ".\n\n").replace("wiki", "[wiki]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/wiki)") + "\n"
          file_content += f"![$GITHUB_REPOSITORY]({social_img})\n"
          return file_content
        if __name__ == "__main__":
          open("Home.md", "w+").write(str(get_content()))                    
        EOF
    - name: Class UML file
      run: |
        cd wiki
        echo "## :octocat: Class UML :octocat:" > Class-UML.md
        echo "![Class UML](https://raw.githubusercontent.com/$GITHUB_REPOSITORY/$(echo ${GITHUB_REF#refs/heads/})/docs/${{ github.event.repository.name }}-Class-UML.svg)" >> Class-UML.md
    - name: CHANGELOG file
      run: |
        cp repo/debian/changelog wiki/
        cd wiki
        sed -i 's/Changelog/:octocat: Changelog :octocat:/g' changelog
        sed -i 's/# /## /g' changelog
    - name: Directory structure file
      run: |
        cd wiki
        sudo apt install tree -y
        echo "## :octocat: Directory structure :octocat:" > Directory-Structure.md
        echo "" >> Directory-Structure.md
        echo "\`\`\`" >> Directory-Structure.md
        tree ../repo >> Directory-Structure.md
        echo "\`\`\`" >> Directory-Structure.md
        sed -i 's/├── debian/├── debian # debian control code/g' Directory-Structure.md
        sed -i 's/bin/bin # source code/g' Directory-Structure.md
        sed -i 's/docs/docs # documentation/g' Directory-Structure.md
    - name: Rebuild the manager-createstructure locally
      run: |
        cp repo/docs/.templates/Rebuild-the-manager-createstructure-locally.md wiki/Rebuild-the-manager-createstructure-locally.md
    - name: _Footer file
      run: |
        paste repo/docs/.templates/_Footer.md > wiki/_Footer.md
        cat wiki/_Footer.md
    - name: _Header file
      run: |
        cp repo/docs/.templates/_Header.md wiki/_Header.md
    - name: Recreate README.md
      run: |
        paste wiki/_Header.md \
              wiki/Home.md \
              wiki/Class-UML.md \
              wiki/Directory-Structure.md \
              wiki/changelog \
              wiki/Rebuild-the-manager-createstructure-locally.md \
              wiki/_Footer.md \
              > repo/docs/README.md
        sed -i 's/:octocat://g' repo/docs/README.md
        cat repo/docs/README.md
    - name: git add & commit & upload wiki
      continue-on-error: true
      run: |
        {
          ls wiki/.git/ > /dev/null
        } && {
          cd wiki
          git config user.name "$GITHUB_ACTOR"
          git config user.email "help@castellanidavide.it"
          git add *
          git commit -m "Upgrade by automatic action"
          git push https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.wiki.git
        }
    - name: git add & commit & upload repo
      continue-on-error: true
      run: |
        cd repo
        git config user.name "$GITHUB_ACTOR"
        git config user.email "help@castellanidavide.it"
        git add *
        git commit -m "Upgrade by automatic action"
        git push https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git
